syntax enable
set background=dark
colorscheme gruvbox
set tabstop=4
set softtabstop=4
set expandtab
set number
set cursorline
set showmatch
set autoindent
set smartindent
set ai
set backspace=indent,eol,start
set mouse=a
set lazyredraw
